# -*- coding: utf-8 -*-
"""training data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15jMS4-vSyELYeHblS3PeUcNPWtnhdWsm
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/titanic-training-data.csv")

df.shape

df.sample()

df.dtypes

df.isnull().sum()

df.describe(include="all")

df.dtypes

median1=df["Age"].median()
median1

df["Age"].replace(np.nan,median1,inplace=True)
df.isnull().sum()

sns.boxplot(y="Age",data=df)

def remove_outlier(col):
  sorted(col)
  Q1,Q3=col.quantile([0.25,0.75])
  IQR=Q3-Q1
  lower_range=Q1-(1.5*IQR)
  upper_range=Q3+(1.5*IQR)
  return lower_range,upper_range

lowage,highage=remove_outlier(df["Age"])
df["Age"]=np.where(df["Age"]>highage,highage,df["Age"])
df["Age"]=np.where(df["Age"]<lowage,lowage,df["Age"])

sns.boxplot(y="Age",data=df)

#handling categorical data
df=pd.get_dummies(df,columns=[])

df=pd.get_dummies(df)

df.head()

